"""
End-to-end test for ewankb build + query pipeline using the mall fixture project.

Usage: pytest tests/test_mall_e2e.py -v

Prerequisites:
  - ANTHROPIC_API_KEY set in environment, or ~/.claude/settings.json with credentials
  - ewankb installed (pip install -e .)

Note: LLM-dependent steps (AI domain refinement, document extraction, overview
generation) may fail due to API rate limits or timeouts. The test tolerates partial
success and verifies that core non-LLM functionality (graph build, BM25, query) works.
"""

import json
import os
import shutil
from pathlib import Path

import pytest

EWANKB_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_DIR = EWANKB_ROOT / "tests" / "fixtures" / "商城项目"
KB_OUTPUT_DIR = Path("/tmp/ewankb_test_mall")

# Resolve LLM config from environment or Claude Code settings
_llm_api_key = os.environ.get("ANTHROPIC_API_KEY", "")
_llm_base_url = os.environ.get("ANTHROPIC_BASE_URL", "")
_llm_model = os.environ.get("ANTHROPIC_MODEL", "")

if not _llm_api_key:
    cc_settings = Path.home() / ".claude" / "settings.json"
    if cc_settings.exists():
        with open(cc_settings, encoding="utf-8") as f:
            cc_data = json.load(f)
        env = cc_data.get("env", {})
        _llm_api_key = env.get("ANTHROPIC_AUTH_TOKEN", "")
        _llm_base_url = env.get("ANTHROPIC_BASE_URL", _llm_base_url)
        _llm_model = env.get("ANTHROPIC_DEFAULT_SONNET_MODEL", _llm_model or "claude-haiku-4-5-20251001")

pytestmark = pytest.mark.skipif(
    not _llm_api_key,
    reason="No API key available. Set ANTHROPIC_API_KEY or configure ~/.claude/settings.json",
)


def _reset_config_caches():
    """Reset config_loader singleton caches so EWANKB_DIR is re-read."""
    import ewankb.tools.config_loader as cfg
    cfg._global_cfg = None
    cfg._project_cfg = None
    cfg._llm_cfg = None


def _setup_kb_dir():
    """Initialize a KB directory at KB_OUTPUT_DIR with fixture source data."""
    if KB_OUTPUT_DIR.exists():
        shutil.rmtree(KB_OUTPUT_DIR)

    KB_OUTPUT_DIR.mkdir(parents=True)

    for d in [
        "source/repos", "source/docs", "domains/_meta",
        "knowledgeBase", "graph/.cache",
    ]:
        (KB_OUTPUT_DIR / d).mkdir(parents=True, exist_ok=True)

    shutil.copytree(FIXTURE_DIR / "source" / "repos", KB_OUTPUT_DIR / "source" / "repos", dirs_exist_ok=True)
    shutil.copytree(FIXTURE_DIR / "source" / "docs", KB_OUTPUT_DIR / "source" / "docs", dirs_exist_ok=True)
    shutil.copytree(
        EWANKB_ROOT / "ewankb" / "templates" / "knowledgeBase",
        KB_OUTPUT_DIR / "knowledgeBase", dirs_exist_ok=True,
    )

    os.environ["EWANKB_DIR"] = str(KB_OUTPUT_DIR)
    _reset_config_caches()

    from ewankb.tools.config_loader import create_project_config, get_global_config
    gcfg = get_global_config()
    create_project_config(KB_OUTPUT_DIR, "商城项目业务知识库")

    with open(KB_OUTPUT_DIR / "llm_config.json", "w", encoding="utf-8") as f:
        json.dump({
            "api_key": _llm_api_key,
            "base_url": _llm_base_url,
            "model": _llm_model,
            "api_protocol": "anthropic",
        }, f, indent=2, ensure_ascii=False)

    (KB_OUTPUT_DIR / ".gitignore").write_text("graph/.cache/\nknowledgeBase/_state/\n.env\nllm_config.json\n")
    print(f"KB directory initialized at {KB_OUTPUT_DIR}", flush=True)


def test_full_pipeline():
    """Run full ewankb pipeline: init -> discover -> build -> graph -> query."""
    _setup_kb_dir()

    # ── Step 1: Discover domains ──
    os.environ["EWANKB_DIR"] = str(KB_OUTPUT_DIR)
    _reset_config_caches()

    from ewankb.tools.discover.discover_domains import discover
    result = discover(KB_OUTPUT_DIR, use_ai=True)
    domain_list = result.get("domain_list", [])
    print(f"Discovered {len(domain_list)} domains: {domain_list}", flush=True)
    assert len(domain_list) >= 3, f"Expected ≥3 domains, got {len(domain_list)}"

    domains_file = KB_OUTPUT_DIR / "domains" / "_meta" / "domains.json"
    assert domains_file.exists(), "domains.json not created"
    with open(domains_file, encoding="utf-8") as f:
        data = json.load(f)
    all_english_keys = []
    for info in data.get("domains", {}).values():
        all_english_keys.extend(info.get("english_keys", []))
    assert "order" in all_english_keys, f"order not in english_keys: {all_english_keys}"

    # ── Step 2: Build knowledge base (tolerate partial LLM failures) ──
    os.environ["EWANKB_DIR"] = str(KB_OUTPUT_DIR)
    _reset_config_caches()
    os.chdir(KB_OUTPUT_DIR)

    from ewankb.__main__ import cmd_knowledgebase
    cmd_knowledgebase(skip_discover=True)

    # Verify build output structure
    assert (KB_OUTPUT_DIR / "domains" / "_meta" / "domains.json").exists()
    domain_dirs = [d for d in (KB_OUTPUT_DIR / "domains").iterdir()
                   if d.is_dir() and not d.name.startswith("_")]
    assert len(domain_dirs) >= 3, f"Not enough domain dirs: {len(domain_dirs)}"
    # Each domain should have README.md (generated by LLM)
    for d in domain_dirs:
        assert (d / "README.md").exists(), f"Missing README.md in {d.name}"
    assert (KB_OUTPUT_DIR / "knowledgeBase" / "_state" / "bm25_index.pkl").exists()
    # KnowledgeBase should have doc type dirs with content
    kb_types = ["需求文档", "接口文档", "业务规则", "测试用例", "研发设计文档"]
    found_types = []
    for t in kb_types:
        t_dir = KB_OUTPUT_DIR / "knowledgeBase" / t
        if t_dir.exists() and any(f for f in t_dir.iterdir() if f.is_file()):
            found_types.append(t)
    assert len(found_types) >= 3, f"Expected ≥3 doc types, got {found_types}"

    # ── Step 3: Build graph (non-LLM, always works) ──
    os.environ["EWANKB_DIR"] = str(KB_OUTPUT_DIR)
    _reset_config_caches()

    from ewankb.tools.build_graph.graph_builder import build_graph
    graph = build_graph(
        source_dir=KB_OUTPUT_DIR / "source",
        domains_dir=KB_OUTPUT_DIR / "domains",
        graph_dir=KB_OUTPUT_DIR / "graph",
    )
    nodes = graph.get("nodes", [])
    links = graph.get("links", [])
    meta = graph.get("metadata", {})
    print(f"Graph: {meta.get('num_nodes', len(nodes))} nodes, {meta.get('num_links', len(links))} links", flush=True)
    assert len(nodes) > 0, "Graph has no nodes"
    assert (KB_OUTPUT_DIR / "graph" / "graph.json").exists()

    # ── Step 4: Query graph (code nodes always exist) ──
    from ewankb.context import KBContext
    ctx = KBContext(KB_OUTPUT_DIR)
    ctx.load_graph()

    # English keyword matches AST code nodes (always works)
    graph_result = ctx.query_graph("OrderService", traversal="bfs", verbose=True)
    matched = graph_result.get("matched_start_nodes", [])
    visited = graph_result.get("nodes", [])
    print(f"Query 'OrderService': {len(matched)} matched, {len(visited)} visited", flush=True)
    assert len(matched) > 0 or len(visited) > 0, "Graph query returned no results"

    # ── Step 5: Query KB (BM25 always works once index is built) ──
    ctx.load_bm25()
    assert ctx.docs is not None and len(ctx.docs) > 0, "BM25 has no docs"

    kb_result = ctx.query_kb("库存校验规则", max_results=5)
    print(f"Query-KB '库存校验规则': {len(kb_result)} chars", flush=True)
    assert len(kb_result) > 50, "KB query returned too short result"

    # ── Cleanup ──
    if os.environ.get("KEEP_OUTPUT", "") == "1":
        print(f"KB output preserved at {KB_OUTPUT_DIR}", flush=True)
    else:
        shutil.rmtree(KB_OUTPUT_DIR)
        print("E2E test passed, cleanup done.", flush=True)


def test_frontend_association():
    """Verify Java constant resolution, frontend constant resolution, and frontend→domain association."""
    _setup_kb_dir()

    os.environ["EWANKB_DIR"] = str(KB_OUTPUT_DIR)
    _reset_config_caches()

    # Run discover first to create domains.json (needed for build_code_index)
    from ewankb.tools.discover.discover_domains import discover
    result = discover(KB_OUTPUT_DIR, use_ai=False)
    domain_list = result.get("domain_list", [])
    print(f"Discovered {len(domain_list)} domains: {domain_list}", flush=True)
    assert len(domain_list) >= 3, f"Expected ≥3 domains, got {len(domain_list)}"

    # Reload config caches after discover
    os.environ["EWANKB_DIR"] = str(KB_OUTPUT_DIR)
    _reset_config_caches()

    import importlib
    import ewankb.tools.extract_kb.enrich_kb as enrich_mod
    importlib.reload(enrich_mod)
    import ewankb.tools.config_loader as cfg_mod
    importlib.reload(cfg_mod)

    resolve_java_endpoint_constants = enrich_mod.resolve_java_endpoint_constants
    resolve_frontend_constants = enrich_mod.resolve_frontend_constants
    build_code_index = enrich_mod.build_code_index
    build_frontend_index = enrich_mod.build_frontend_index
    get_repos_dir = cfg_mod.get_repos_dir

    repos_dir = get_repos_dir()

    # ── 1. Java constant resolution ──
    java_constants = resolve_java_endpoint_constants(repos_dir)
    print(f"Java constants: {len(java_constants)} entries", flush=True)
    assert len(java_constants) > 0, "No Java endpoint constants found"
    # OrderApi.BASE should resolve to "/api/orders"
    assert "OrderApi.BASE" in java_constants, f"OrderApi.BASE not found: {list(java_constants.keys())}"
    assert java_constants["OrderApi.BASE"] == "/api/orders", f"OrderApi.BASE value wrong: {java_constants['OrderApi.BASE']}"
    # OrderApi.LIST should resolve via concatenation
    assert "OrderApi.LIST" in java_constants, f"OrderApi.LIST not found: {list(java_constants.keys())}"
    assert java_constants["OrderApi.LIST"] == "/api/orders/list", f"OrderApi.LIST value wrong: {java_constants['OrderApi.LIST']}"
    # PaymentApi.CREATE should resolve via concatenation
    assert "PaymentApi.CREATE" in java_constants, f"PaymentApi.CREATE not found"
    assert java_constants["PaymentApi.CREATE"] == "/api/payments/create"

    # ── 2. Frontend constant resolution ──
    fe_constants = resolve_frontend_constants(repos_dir)
    print(f"Frontend constants: {len(fe_constants)} entries", flush=True)
    assert len(fe_constants) > 0, "No frontend constants found"
    assert "OrderApi.LIST" in fe_constants, f"OrderApi.LIST not found in FE constants: {list(fe_constants.keys())}"
    assert fe_constants["OrderApi.LIST"] == "/api/orders", f"FE OrderApi.LIST value wrong: {fe_constants['OrderApi.LIST']}"

    # ── 3. Build code index with Java constants ──
    code_idx, kw_idx, ep_idx = build_code_index(java_constants)
    assert len(code_idx) > 0, "code_idx empty"
    # Verify OrderController endpoints include resolved constant paths
    order_domain_files = None
    for domain, files in code_idx.items():
        for file_str, info in files.items():
            if "OrderController" in file_str:
                order_domain_files = files
                break
    assert order_domain_files is not None, "OrderController not found in code_idx"
    order_ctrl_info = None
    for file_str, info in order_domain_files.items():
        if "OrderController" in file_str:
            order_ctrl_info = info
            break
    assert order_ctrl_info is not None
    assert "/api/orders" in order_ctrl_info["endpoints"], f"OrderController endpoints: {order_ctrl_info['endpoints']}"
    # Constant-resolved paths should not be duplicated with class_prefix
    for ep in order_ctrl_info["endpoints"]:
        assert not ep.startswith("/api/orders/api/orders"), f"Duplicated class_prefix in endpoint: {ep}"

    # ── 4. Build frontend index ──
    frontend_idx = build_frontend_index(repos_dir, code_idx, ep_idx, fe_constants)
    print(f"Frontend index: {len(frontend_idx)} domains with frontend", flush=True)
    assert len(frontend_idx) >= 2, f"Expected ≥2 domains with frontend, got {len(frontend_idx)}: {list(frontend_idx.keys())}"

    # ── 5. OrderList.vue should be associated to a domain containing "order" ──
    order_fe_found = False
    for domain, fe_entries in frontend_idx.items():
        for entry in fe_entries:
            if "OrderList" in entry.get("component_name", "") or "OrderList" in entry.get("file_str", ""):
                # Check the domain has "order" english_key
                order_fe_found = True
                assert "/api/orders" in entry.get("api_paths", []), f"OrderList api_paths missing /api/orders: {entry['api_paths']}"
                print(f"OrderList.vue → domain '{domain}', api_paths: {entry['api_paths']}", flush=True)
                break
    assert order_fe_found, "OrderList.vue not found in frontend_idx"

    # ── Cleanup ──
    if os.environ.get("KEEP_OUTPUT", "") == "1":
        print(f"KB output preserved at {KB_OUTPUT_DIR}", flush=True)
    else:
        shutil.rmtree(KB_OUTPUT_DIR)
        print("Frontend association test passed, cleanup done.", flush=True)